name: Java CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Test with Gradle
      run: ./gradlew clean test
    - name: Set up Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
    - name: Run Trivy scan
      run: trivy fs --exit-code 1 --severity HIGH,CRITICAL . | tee trivy-report.txt
    - name: Generate Trivy scan summary report
      run: |
        trivy fs --severity HIGH,CRITICAL --format json . > trivy-summary.json
        jq -r '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | "\(.PkgName) \(.VulnerabilityID) \(.Severity) \(.Title)"' trivy-summary.json > trivy-summary.txt
    - name: Display Trivy scan results
      if: always()
      run: cat trivy-report.txt
    - name: Display Trivy scan summary report
      if: always()
      run: cat trivy-summary.txt
    - name: Block merge if tests fail
      if: failure()
      run: exit 1
