name: Trivy Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Run Trivy scan
      id: trivy-scan
      run: trivy fs --exit-code 1 --severity HIGH,CRITICAL . | tee trivy-report.txt

    - name: Generate Trivy scan summary report
      id: trivy-summary
      run: |
        trivy fs --severity HIGH,CRITICAL --format json . > trivy-summary.json
        if [ -s trivy-summary.json ]; then
          jq -r '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | [.VulnerabilityID, .PkgName, .InstalledVersion, .FixedVersion, .Severity, .Title] | @tsv' trivy-summary.json > trivy-summary.txt
        else
          echo "trivy-summary.json is empty or not properly formatted."
          exit 1

    - name: Display Trivy scan results
      if: always()
      run: cat trivy-report.txt

    - name: Display Trivy scan summary report
      if: always()
      run: cat trivy-summary.txt
